[build]
target = "avr-atmega328p.json"

[unstable]
build-std = ["core"]

[env]
AVR_CPU_FREQUENCY_HZ = "16_000_000"

[target.'cfg(all(target_arch = "avr", target_os = "none"))']
rustflags = ["-C", "inline-threshold=123"]
